# Generated by Django 4.1 on 2022-08-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assuntos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='data_alteracao',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='data_inclusao',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='hora_alteracao',
        ),
        migrations.RemoveField(
            model_name='assunto',
            name='hora_inclusao',
        ),
        migrations.DeleteModel(
            name='HistoricalAssunto',
        ),
    ]
