# Generated by Django 4.1 on 2022-08-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assuntos', '0003_assunto_folha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='folha',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
