# Generated by Django 4.1 on 2022-08-14 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidades', '0002_unidade_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='usuarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
