# Generated by Django 4.1 on 2022-08-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidades', '0003_alter_unidade_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionariosUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='unidade',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='unidades', through='unidades.FuncionariosUnidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funcionariosunidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.unidade'),
        ),
    ]
