# Generated by Django 4.1 on 2022-08-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_funcionariosunidade_remove_unidade_usuarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='funcionarios',
        ),
        migrations.DeleteModel(
            name='FuncionariosUnidade',
        ),
    ]
