# Generated by Django 4.1 on 2022-08-15 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidades', '0005_remove_unidade_funcionarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='unidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
