# Generated by Django 4.1 on 2022-08-21 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assuntos', '0002_remove_assunto_data_alteracao_and_more'),
        ('unidades', '0006_unidade_funcionarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True)),
                ('anonimo', models.BooleanField(default=False, verbose_name='Anônimo?')),
                ('descricao_ocorrencia', models.TextField(blank=True, null=True, verbose_name='Descrição da Ocorrência')),
                ('assunto', models.ForeignKey(limit_choices_to={'is_leaf_node': True}, on_delete=django.db.models.deletion.PROTECT, to='assuntos.assunto')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enderecos.endereco', verbose_name='Endereço')),
                ('solicitante', models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidade_atual', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOcorrencia',
            fields=[
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.TimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True)),
                ('anonimo', models.BooleanField(default=False, verbose_name='Anônimo?')),
                ('descricao_ocorrencia', models.TextField(blank=True, null=True, verbose_name='Descrição da Ocorrência')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assunto', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_leaf_node': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assuntos.assunto')),
                ('endereco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enderecos.endereco', verbose_name='Endereço')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidade_atual', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'historical ocorrencia',
                'verbose_name_plural': 'historical ocorrencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
