# Generated by Django 4.1 on 2022-08-23 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assuntos', '0003_assunto_folha'),
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalocorrencia',
            name='assunto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assuntos.assunto'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assuntos.assunto'),
        ),
    ]
