# Generated by Django 4.1 on 2022-08-23 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assuntos', '0004_alter_assunto_folha'),
        ('ocorrencias', '0002_alter_historicalocorrencia_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalocorrencia',
            name='assunto',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'folha': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assuntos.assunto'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='assunto',
            field=models.ForeignKey(limit_choices_to={'folha': True}, on_delete=django.db.models.deletion.PROTECT, to='assuntos.assunto'),
        ),
    ]
