# Generated by Django 4.1 on 2022-08-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_alter_historicalocorrencia_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalocorrencia',
            name='ano',
            field=models.PositiveIntegerField(default='2022', editable=False),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ano',
            field=models.PositiveIntegerField(default='2022', editable=False),
        ),
    ]
