# Generated by Django 4.1 on 2022-08-27 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocorrencias', '0005_alter_ocorrencia_unidade_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalocorrencia',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='solicitante',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
